config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  # Associations
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  # Validations
  validates :name, uniqueness: true, presence: true

  # Scopes
  scope :search_by, ->(query) { where('name iLIKE ?', "%#{query}%") }

  # Uploaders
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  # Associations
  belongs_to :ingredient
  belongs_to :cocktail

  # Validations
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Associations
  has_many :doses
  has_many :cocktails, through: :doses

  # Validations
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.search_by(params[:query]).sort_by { |cocktail| cocktail.id }
    if params[:query].present?
      @query = 1
    else
      @query = 0
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new"
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.delete
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :query, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container pt-3">
  <h2>Which cocktail would you like to modify ?</h2>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="container">
    <div class="empty"></div>
    <div class="banner-titles">
      <h1>Bartendr</h1>
      <h2>Quick access to your favorite cocktails</h2>
    </div>
    <div class="see-cocktails">
      <h4>Browse all of our cocktails</h4>
      <i class="fas fa-chevron-down"></i>
    </div>
  </div>
</div>
<div class="container" id="cocktails">
  <h2 class="text-center my-5">Check out our cocktails !</h2>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.present? %>
      <% url = cl_image_path cocktail.photo, height: 300, width: 300, crop: :fill %>
    <% else %>
      <% url = cl_image_path "generic_l79l58", height: 300, width: 300, crop: :fill %>
    <% end %>
      <div class="col-4">
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card-category my-2", id="cocktail-card", style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= url %>')">
            <%= cocktail.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @query == 1 %>
    <script>
      window.scrollBy({
      top: window.innerHeight,
      left: 0,
      behavior: 'smooth'
    })
    </script>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container pt-3 d-flex">

  <div class="cocktail-img mr-3">
    <%= cl_image_tag @cocktail.photo, height: 500, width: 500 %>
  </div>
  <div class="cocktail-info ml-3">
    <div class="cocktail-info-text">
      <div class="cocktail-name d-flex align-items-center">
        <h1 class="mr-3"><%= @cocktail.name %></h1>
        <%= link_to edit_cocktail_path(@cocktail) do %>
          <i class="fas fa-pencil-alt fa-lg mr-3"></i>
        <% end %>
      </div>
      <div class="cocktail-doses">
        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li><%= "#{dose.ingredient.name} - #{dose.description}" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient, input_html: { class: 'select2' } %>
      <%= f.input :description %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bartendr</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'components/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>